In [ ]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 120
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

In [ ]:
mob = pd.read_csv('drive/MyDrive/Data Sets/mobile.csv')

In [ ]:
mob

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

### Question 1

The data for this project is ‘mobile.csv,’ and the goal is to predict the device's price range given the mobile device characteristics. You will implement different classifiers, including Logistic Regression, Support Vector Machines, K-Nearest neighbors, and Random Forest.

    Create one single train/test split with a test size of 30% of the total number of observations and a random_state=123. You will decide if you need to properly scale the data, fit each classifier on the train set, and measure the test's overall accuracy. For each classifier that requires method-specific hyper-parameters, you will determine the best choice from the following ranges:


    Logistic Regression: no need to tune anything. Take solver=‘lbfgs’ and max_iter=10000.’
    Support Vector Machine - polynomial kernel. Test degrees 1,2 and 3 and a range for C between 1 and 75 with increments of 0.5
    Support Vector Machine - radially basis kernel. Test gamma between 0.0005 and 0.01 in 0.0001 increments and a range for C between 1 and 75 with increments of 0.5
    K-Nearest neighbors - test the performance for any number of neighbors between 3 and 125. The weights could be either ‘uniform’ or ‘distance.’
    Random Forest - test the performance for any number of trees between 10 and 500 and the max depth for any value between 3 and 100.


After determining the best choice of hyperparameters for each method, show confusion matrices with the best results.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix as CM

In [ ]:
X = mob.iloc[:,:-1].values
y = mob.iloc[:,-1].values

In [ ]:
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size=0.3, random_state=123)

In [ ]:
scale = StandardScaler()

In [ ]:
xTrain_scaled = scale.fit_transform(xTrain)
xTest_scaled = scale.transform(xTest)

In [ ]:
#Logisitic Regression
model = LogisticRegression(solver='lbfgs', max_iter = 10000)
model.fit(xTrain, yTrain)
model.score(xTest, yTest)
yPred = model.predict(xTest)
cm = confusion_matrix(yTest, yPred)
cm, model.score(xTest, yTest)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(array([[130,  18,   0,   0],
        [ 20, 102,  28,   4],
        [  0,  24,  96,  43],
        [  0,   0,  15, 120]]),
 0.7466666666666667)

In [ ]:
#SVM polynomial
from sklearn.svm import SVR
cVal = np.arange(1, 75, 0.5)
prev1 = 0
prev2 = 0
prev3 = 0
#For degree 1
for C in cVal:
  model = SVR(kernel = 'poly', degree = 1, C = C)
  model.fit(xTrain, yTrain)
  if model.score(xTest, yTest) > prev1:
    prev1 = model.score(xTest, yTest)
    cBest1 = C
print(prev1)
print(cBest1)
#for degree 2
for C in cVal:
  model = SVR(kernel = 'poly', degree = 2, C = C)
  model.fit(xTrain, yTrain)
  if model.score(xTest, yTest) > prev2:
    prev2 = model.score(xTest, yTest)
    cBest2 = C
print(prev2)
print(cBest2)
#For degree 3
for C in cVal:
  model = SVR(kernel = 'poly', degree = 3, C = C)
  model.fit(xTrain, yTrain)
  if model.score(xTest, yTest) > prev3:
    prev3 = model.score(xTest, yTest)
    cBest3 = C
print(prev3)
print(cBest3)

0.9145018487118254
7.0
0.8879946130018794
74.5
0.8507910628396481
74.5


In [ ]:
#Most accurate is first degree with C = 7
from sklearn.svm import SVR
model = SVR(kernel = 'poly', degree = 1, C = 7)
model.fit(xTrain, yTrain)
model.score(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[  0,   0,   0,   0,   0,   0],
       [  7, 129,  12,   0,   0,   0],
       [  0,   2, 149,   3,   0,   0],
       [  0,   0,  12, 148,   3,   0],
       [  0,   0,   0,  19, 106,  10],
       [  0,   0,   0,   0,   0,   0]])

In [ ]:
#SVM radial
from sklearn.svm import SVR
cVal = np.arange(1, 75, 0.5)
gamVal = np.arange(0.0005, 0.01, 0.0001)
prev = 0
for C in cVal:
  for gamma in gamVal:
    model = SVR(kernel = 'rbf', C = C, gamma = gamma)
    model.fit(xTrain, yTrain)
    if model.score(xTest, yTest) > prev:
      prev = model.score(xTest, yTest)
      cBest = C
      gBest = gamma
print(prev)
print(cBest)
print(gBest)

0.000614604717903422
1.5
0.0005


In [ ]:
#Most accurate model is when C = 1.5 and gamma = 0.0005
from sklearn.svm import SVR
model = SVR(kernel = 'rbf', C = 1.5, gamma = 0.0005)
model.fit(xTrain, yTrain)
model.score(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[  0,   1, 147,   0],
       [  0,   1, 153,   0],
       [  0,   0, 163,   0],
       [  0,   0, 135,   0]])

In [ ]:
#K-nearest neighbors
from sklearn import neighbors
prev = 0
for i in range(3, 126):
  model = neighbors.KNeighborsClassifier(n_neighbors = i, weights= 'uniform')
  model.fit(xTrain, yTrain)
  if model.score(xTest, yTest) > prev:
    prev = model.score(xTest, yTest)
    nBest = i
print(prev)
print(nBest)

0.94
7


In [ ]:
#Most accurate is neighbors = 7
from sklearn import neighbors
model = neighbors.KNeighborsClassifier(n_neighbors = 7, weights= 'uniform')
model.fit(xTrain, yTrain)
model.score(xTest, yTest)
yPred = model.predict(xTest)
cm = confusion_matrix(yTest, yPred)
cm

array([[145,   3,   0,   0],
       [  4, 148,   2,   0],
       [  0,   6, 144,  13],
       [  0,   0,   8, 127]])

In [ ]:
#Random Forest
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
num = np.arange(10, 501)
depth = np.arange(3, 101)
h_names = ['n_estimators','max_depth']
model = RandomForestClassifier(random_state = 123)

In [ ]:
def GS_Anneal(model,h_names,h1,h2,xtrain,ytrain,xtest,ytest): # h_names means the names of the hyperparameters
  # Here we have an implementation of Simmulated Annealing in Two Dimensions
  MIN_IND1 = 0
  MAX_IND1 = len(h1)
  MIN_IND2 = 0
  MAX_IND2 = len(h2)
  STEP_SIZE = 7    # Std of gaussian steps
  COOLING = 0.98    # T_{n+1} = T_{n}*COOLING, i.e. geometric cooling
  def cost_function(model):
    #pipe = Pipeline([['Scale',scale],['Model',model]])
    #k_fold = cross_val_score(estimator=model,X=x,y=y,cv=10,scoring='neg_mean_squared_error')
    model.fit(xtrain,ytrain)
    return 1 - model.score(xtest,ytest)


  def random_start():
      i = np.random.randint(MIN_IND1,MAX_IND1-1)
      j = np.random.randint(MIN_IND2,MAX_IND2-1)
      pos = [i,j]
      return pos


  def random_neighbour(pos,T):
      i = pos[0]
      j = pos[1]
      raw_i = np.random.normal()*STEP_SIZE*T
      delta_i = np.floor(raw_i).astype(int)
      raw_j = np.random.normal()*STEP_SIZE*T
      delta_j = np.floor(raw_j).astype(int)
      if (delta_i == 0) & (delta_j == 0):
        delta_i = np.sign(raw_i).astype(int)
        delta_j = np.sign(raw_j).astype(int)
      new_i = min(MAX_IND1-1, max(MIN_IND1, i+delta_i))
      new_j = min(MAX_IND2-1, max(MIN_IND2, j+delta_j))
      new_pos = [new_i,new_j]
      return new_pos


  def acceptance_probability(cost, new_cost, temperature):
      if new_cost < cost:
          return 1
      else:
          p = np.exp(-(new_cost - cost) / temperature)
          return p


  def locate_min(a):
      smallest = min(a)
      return smallest, [index for index, element in enumerate(a) if smallest == element]

  def annealing(pos0 = random_start()):
      # Start with a random configuration
      # alpha = random_start()
      i = pos0[0]
      j = pos0[1]
      # All layers will have the same number of nodes (keep the example from getting too complicated)
      model.set_params(**{list(h_names)[0]:h1[i-1],list(h_names)[1]:h2[j-1]})

      # Compute the cost function (in this case, 1-accuracy)
      cost = cost_function(model)

      # Keep lists of results, start with the current
      states1, states2, costs = [h1[i-1]], [h2[j-1]], [cost]
      T = 1
      pos = pos0
      while T > 1e-10:
          new_pos = random_neighbour(pos,T)
          i = new_pos[0]
          j = new_pos[1]
          model.set_params(**{list(h_names)[0]:h1[i-1],list(h_names)[1]:h2[j-1]})
          new_cost = cost_function(model)
          if acceptance_probability(cost, new_cost, T) > np.random.random():
              cost = new_cost
              pos = new_pos
              states1.append(h1[pos[0]])
              states2.append(h2[pos[1]])
              costs.append(cost)
          T = T*COOLING
      return model,np.column_stack([states1,states2]),costs
  m,states,costs = annealing()
  return states, costs

In [ ]:
states, costs = GS_Anneal(model, h_names, num, depth, xTrain, yTrain, xTest, yTest)

In [ ]:
best = np.argmax(costs)
best #25
states[25]
#Best is 397 nodes and depth of 4

array([397,   4])

In [ ]:
model = RandomForestClassifier(random_state = 123, max_depth = 4, n_estimators = 397)
model.fit(xTrain, yTrain)
yPred = model.predict(xTest)
cm = confusion_matrix(yTest, yPred)
cm, model.score(xTest, yTest)

(array([[143,   5,   0,   0],
        [ 20, 112,  22,   0],
        [  0,  34,  86,  43],
        [  0,   0,   3, 132]]),
 0.7883333333333333)

### Question 2

2. Repeat all the steps from 1) with complete 5-Fold cross-validations, report the choice of the best hyperparameters found, and rank the different methods according to the overall cross-validated accuracy.



In [ ]:
#Logisitic Regression, no need to tune hyperparameters
from sklearn.model_selection import cross_val_score
model = LogisticRegression(solver='lbfgs', max_iter = 10000)
model.fit(xTrain, yTrain)
model.score(xTest, yTest)
yPred = model.predict(xTest)
cm = confusion_matrix(yTest, yPred)
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
cm, np.mean(scores)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

(array([[130,  18,   0,   0],
        [ 20, 102,  28,   4],
        [  0,  24,  96,  43],
        [  0,   0,  15, 120]]),
 0.7630000000000001)

In [ ]:
#overall accuracy = 76.3%

In [ ]:
#SVM polynomial
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, KFold
#Degree 1
cVal = np.arange(1, 75, 0.5)
param_grid = {'C': cVal}
model = SVR(kernel = 'poly', degree = 1)
grid_search = GridSearchCV(model, param_grid=param_grid, cv=KFold(n_splits=5, shuffle=True, random_state=123))
grid_search.fit(X, y)
print("Best hyperparameters found:", grid_search.best_params_)

Best hyperparameters found: {'C': 13.5}


In [ ]:
model = SVR(kernel = 'poly', degree = 1, C = 13.5)
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores) #91.69% accuracy

0.91691119922708

In [ ]:
model.fit(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[  0,   0,   0,   0,   0,   0],
       [  8, 125,  15,   0,   0,   0],
       [  0,   1, 152,   1,   0,   0],
       [  0,   0,  10, 153,   0,   0],
       [  0,   0,   0,  26, 100,   9],
       [  0,   0,   0,   0,   0,   0]])

In [ ]:
#Degree 2
cVal = np.arange(1, 75, 0.5)
param_grid = {'C': cVal}
model = SVR(kernel = 'poly', degree = 2)
grid_search = GridSearchCV(model, param_grid=param_grid, cv=KFold(n_splits=5, shuffle=True, random_state=123))
grid_search.fit(X, y)
print("Best hyperparameters found:", grid_search.best_params_)

Best hyperparameters found: {'C': 74.5}


In [ ]:
from sklearn.svm import SVR
model = SVR(kernel = 'poly', degree = 2, C = 74.5)
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores)  #89.19% accuracy

0.8919696868606932

In [ ]:
#Degree 3
cVal = np.arange(1, 75, 0.5)
param_grid = {'C': cVal}
model = SVR(kernel = 'poly', degree = 3)
grid_search = GridSearchCV(model, param_grid=param_grid, cv=KFold(n_splits=5, shuffle=True, random_state=123))
grid_search.fit(X, y)
print("Best hyperparameters found:", grid_search.best_params_)

Best hyperparameters found: {'C': 74.5}


In [ ]:
model = SVR(kernel = 'poly', degree = 3, C = 74.5)
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores)  #85.69% accuracy

0.8569917744957148

In [ ]:
#The best combination of degree and hyperparameter is degree 1 and C = 13.5 with 91.69% accuracy

In [ ]:
model = SVR(kernel = 'poly', degree = 1, C = 13.5)
model.fit(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[  0,   0,   0,   0,   0,   0],
       [  8, 125,  15,   0,   0,   0],
       [  0,   1, 152,   1,   0,   0],
       [  0,   0,  10, 153,   0,   0],
       [  0,   0,   0,  26, 100,   9],
       [  0,   0,   0,   0,   0,   0]])

In [ ]:
#SVM Radial
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, KFold
cVal = np.arange(1, 10, 0.5)
gamVal = np.arange(0.0005, 0.001, 0.0001)
param_grid = {'C': cVal, 'gamma': gamVal}
model = SVR(kernel = 'rbf')
grid_search = GridSearchCV(model, param_grid = param_grid, cv = KFold(n_splits=5, shuffle=True, random_state=123))
grid_search.fit(X, y)
print("Best hyperparameters found:", grid_search.best_params_)

Best hyperparameters found: {'C': 1.5, 'gamma': 0.0005}


In [ ]:
model = SVR(kernel = 'rbf', C = 1.5, gamma = 0.0005)
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores)  #0.16 % accuracy

0.001644206331289122

In [ ]:
model.fit(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[148,   0,   0,   0],
       [  0, 154,   0,   0],
       [  0,   0, 163,   0],
       [  0,   0,   0, 135]])

In [ ]:
#K-Nearest Neighbors
from sklearn import neighbors
from sklearn.model_selection import GridSearchCV, KFold
nNeigh = np.arange(3, 126)
param_grid = {'n_neighbors': nNeigh}
model = neighbors.KNeighborsClassifier(weights= 'uniform')
grid_search = GridSearchCV(model, param_grid = param_grid, cv = KFold(n_splits=5, shuffle=True, random_state=123))
grid_search.fit(X, y)
print("Best hyperparameters found:", grid_search.best_params_)

Best hyperparameters found: {'n_neighbors': 19}


In [ ]:
from sklearn import neighbors
model = neighbors.KNeighborsClassifier(n_neighbors = 19, weights= 'uniform')
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores)  #93.45% accuracy

0.9345000000000001

In [ ]:
model.fit(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[146,   2,   0,   0],
       [  8, 144,   2,   0],
       [  0,   9, 149,   5],
       [  0,   0,  11, 124]])

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
num = np.arange(10, 501)
depth = np.arange(3, 101)
h_names = ['n_estimators','max_depth']
model = RandomForestClassifier(random_state = 123, max_depth = 4, n_estimators = 397)

In [ ]:
kF = KFold(n_splits=5, shuffle=True, random_state=123)
scores = cross_val_score(model, X, y, cv=kF)
np.mean(scores)  #82.50% accuracy

0.825

In [ ]:
model.fit(xTest, yTest)
yPred = model.predict(xTest).round()
cm = confusion_matrix(yTest, yPred)
cm

array([[142,   6,   0,   0],
       [ 13, 128,  13,   0],
       [  0,   4, 159,   0],
       [  0,   0,   9, 126]])